### ISSUE TITLE
Share workspace stay with status Pending join and I can't remove

### ISSUE THREAD

**Issue by ailtonqueiroz** [undistro/zora#229]
## Description
Share workspace stay with status Pending join and I can't remove

## How to Reproduce
1. Go to manager user
2. Click on the user and romve user
3. Select the user 
4. Click on remove user

## Expected Behavior
A remover user

**Comment by lucasjct** [comment]
Hello @ailtonqueiroz, thank you for reporting this. We have deployed a minor fix related to the "Manager Users" page. Could you please provide your feedback if the problem still persists? If the issue continues, please contact us on Slack: [Undistro](https://join.slack.com/t/undistrocommunity/shared_invite/zt-21slyrao4-dTW_XtOB90QVj05txOX6rA). There, we can exchange information for troubleshooting.

**Comment by lucasjct** [comment]
Hello @ailtonqueiroz!

We assumed that the issue was resolved after the latest fix, so we have now closed the issue. However, please feel free to reopen it or contact us on Slack at [Undistro](https://join.slack.com/t/undistrocommunity/shared_invite/zt-21slyrao4-dTW_XtOB90QVj05txOX6rA) if you need further assistance.

Thank you!

**Comment by lucasjct** [comment]
Hello @ailtonqueiroz!

We assumed that the issue was resolved after the latest fix, so we have now closed the issue. However, please feel free to reopen it or contact us on Slack at [Undistro](https://join.slack.com/t/undistrocommunity/shared_invite/zt-21slyrao4-dTW_XtOB90QVj05txOX6rA) if you need further assistance.

Thank you!
